export const FONT_MANAGER = {
  //   poppins
  poppins_thinItalic: "Poppins-ThinItalic",
  poppins_thin: "Poppins-Thin",
  poppins_semiboldItalic: "Poppins-SemiBoldItalic",
  poppins_semibold: "Poppins-SemiBold",
  poppins_regular: "Poppins-Regular",
  poppins_mediumItalic: "Poppins-MediumItalic",
  poppins_medium: "Poppins-Medium",
  poppins_lightItalic: "Poppins-LightItalic",
  poppins_light: "Poppins-Light",
  poppins_italic: "Poppins-Italic",
  poppins_extralightItalic: "Poppins-ExtraLightItalic",
  poppins_extralight: "Poppins-ExtraLight",
  poppins_extraboldItalic: "Poppins-ExtraBoldItalic",
  poppins_extrabold: "Poppins-ExtraBold",
  poppins_boldItalic: "Poppins-BoldItalic",
  poppins_bold: "Poppins-Bold",
  poppins_blackItalic: "Poppins-BlackItalic",
  poppins_black: "Poppins-Black",

  //   roboto
  roboto_thinItalic: "Roboto-ThinItalic",
  roboto_thin: "Roboto-Thin",
  roboto_regular: "Roboto-Regular",
  roboto_mediumItalic: "Roboto-MediumItalic",
  roboto_medium: "Roboto-Medium",
  roboto_lightItalic: "Roboto-LightItalic",
  roboto_light: "Roboto-Light",
  roboto_italic: "Roboto-Italic",
  roboto_boldItalic: "Roboto-BoldItalic",
  roboto_bold: "Roboto-Bold",
  roboto_blackItalic: "Roboto-BlackItalic",
  roboto_black: "Roboto-Black",
};
